-- Catalogul de întrebări din vizita de teren: 6 secțiuni, 23 grupuri.
-- Extras automat din aplicația de teren, nu transcris manual.
-- Întrebările sunt date, nu cod: se pot adăuga sau reordona fără deploy.

create table public.question_sections (
  id              text primary key,
  title           text not null,
  position        integer not null,
  open_by_default boolean not null default false
);

create table public.question_groups (
  id                  text primary key,
  section_id          text references public.question_sections (id) on delete cascade,
  label               text not null,
  -- single / multi = liste de opțiuni; next_step_date și pump_picker au interfață proprie
  kind                text not null check (kind in ('single','multi','next_step_date','pump_picker')),
  allows_note         boolean not null default false,
  -- null = opțiuni din question_options; altfel se citesc din catalog
  options_source      text check (options_source in ('pump_categories','accessory_categories')),
  counts_for_priority boolean not null default false,
  position            integer not null
);

create table public.question_options (
  group_id text not null references public.question_groups (id) on delete cascade,
  id       text not null,
  label    text not null,
  position integer not null,
  primary key (group_id, id)
);

alter table public.question_sections enable row level security;
alter table public.question_groups   enable row level security;
alter table public.question_options  enable row level security;

-- Vocabular comun tuturor organizațiilor: oricine autentificat îl citește.
create policy "secțiuni: citire" on public.question_sections for select to authenticated using (true);
create policy "grupuri: citire"  on public.question_groups   for select to authenticated using (true);
create policy "opțiuni: citire"  on public.question_options  for select to authenticated using (true);

insert into public.question_sections (id, title, position, open_by_default) values
  ('A', 'Esențial (20 de secunde)', 1, true),
  ('B', 'Lucrarea și materialele', 2, true),
  ('C', 'Cum lucrează acum', 3, false),
  ('D', 'De ce și ce l-ar atrage', 4, false),
  ('E', 'Interes pentru pompe și accesorii', 5, false),
  ('F', 'Întrebare pentru owner și etapă', 6, false);

insert into public.question_groups (id, section_id, label, kind, allows_note, options_source, counts_for_priority, position) values
  ('prezenti', 'A', 'Cine a fost prezent', 'multi', true, null, false, 1),
  ('relatie', 'A', 'Relația de azi', 'single', false, null, false, 2),
  ('mod', 'A', 'Cum lucrează', 'single', true, null, false, 3),
  ('interes', 'A', 'Cât de interesat e', 'single', false, null, true, 4),
  ('urmator', 'A', 'Pasul următor', 'single', true, null, false, 5),
  ('cuand', 'A', 'Când faci pasul următor', 'next_step_date', false, null, false, 6),
  ('tip', 'B', 'Tipul lucrării', 'multi', true, null, false, 7),
  ('faza', 'B', 'În ce fază e lucrarea', 'single', false, null, false, 8),
  ('materiale', 'B', 'Materiale cu care lucrează', 'multi', true, null, false, 9),
  ('scule', 'C', 'Scule folosite acum', 'multi', true, null, false, 10),
  ('echipa', 'C', 'Mărimea echipei', 'single', false, null, false, 11),
  ('volum', 'C', 'Câte lucrări are pe lună', 'single', false, null, true, 12),
  ('supr', 'C', 'Suprafață pe zi (dintr-o lucrare recentă)', 'single', false, null, false, 13),
  ('dece', 'D', 'De ce lucrează manual', 'multi', true, null, false, 14),
  ('obiectii', 'D', 'Ce are împotriva mecanizării', 'multi', true, null, false, 15),
  ('pretMod', 'D', 'Cum dă prețul unei lucrări', 'single', false, null, false, 16),
  ('calcul', 'D', 'Și-a făcut vreodată calcul de rentabilitate', 'single', false, null, false, 17),
  ('atragere', 'D', 'Ce l-ar atrage', 'multi', true, null, true, 18),
  ('decide', 'E', 'Cine decide cumpărarea', 'single', false, null, true, 19),
  ('cand', 'E', 'Când ar cumpăra', 'single', false, null, true, 20),
  ('pompeCat', 'E', 'Ce categorii de pompe ar avea nevoie', 'multi', true, 'pump_categories', false, 21),
  ('modele', 'E', 'Modele discutate', 'pump_picker', false, null, false, 22),
  ('accCat', 'E', 'Accesorii de care ar avea nevoie', 'multi', true, 'accessory_categories', false, 23),
  ('esc', 'F', 'Întrebare tehnică pentru owner', 'multi', true, null, false, 24),
  ('etapa', 'F', 'Etapa în care e acum', 'single', false, null, false, 25);

insert into public.question_options (group_id, id, label, position) values
  ('prezenti', 'patron', 'Patron', 1),
  ('prezenti', 'sef', 'Șef de echipă', 2),
  ('prezenti', 'mester', 'Meșter', 3),
  ('prezenti', 'muncitor', 'Muncitor', 4),
  ('prezenti', 'achizitor', 'Achizitor', 5),
  ('prezenti', 'ing', 'Inginer / diriginte', 6),
  ('prezenti', 'client', 'Client final', 7),
  ('relatie', 'slaba', 'Slabă', 1),
  ('relatie', 'buna', 'Bună', 2),
  ('relatie', 'foarte', 'Foarte bună', 3),
  ('mod', 'manual', 'Manual', 1),
  ('mod', 'mixt', 'Mixt', 2),
  ('mod', 'mecanizat', 'Mecanizat', 3),
  ('interes', 'nu', 'Deloc', 1),
  ('interes', 'curios', 'Curios', 2),
  ('interes', 'vezi', 'Vrea să vadă', 3),
  ('interes', 'oferta', 'Vrea ofertă', 4),
  ('interes', 'gata', 'Gata de cumpărare', 5),
  ('urmator', 'revin', 'Revin cu o vizită', 1),
  ('urmator', 'sun', 'Îl sun', 2),
  ('urmator', 'owner', 'Îl leg de un owner (online)', 3),
  ('urmator', 'demo', 'Demo / vede o lucrare', 4),
  ('urmator', 'oferta', 'Trimit ofertă', 5),
  ('urmator', 'asteapta', 'Așteaptă el', 6),
  ('urmator', 'nu', 'Nu mai insist', 7),
  ('tip', 'casa', 'Casă nouă', 1),
  ('tip', 'apart', 'Renovare apartament', 2),
  ('tip', 'bloc', 'Bloc / ansamblu', 3),
  ('tip', 'hala', 'Hală / industrial', 4),
  ('tip', 'fatada', 'Fațade', 5),
  ('tip', 'interior', 'Finisaje interioare', 6),
  ('tip', 'sape', 'Șape / pardoseli', 7),
  ('faza', 'struct', 'Structură', 1),
  ('faza', 'instal', 'Instalații', 2),
  ('faza', 'tencuieli', 'Tencuieli', 3),
  ('faza', 'glet', 'Glet / finisaje', 4),
  ('faza', 'fatada', 'Fațadă', 5),
  ('faza', 'pard', 'Pardoseli', 6),
  ('faza', 'final', 'Final de lucrare', 7),
  ('materiale', 'tencuiala', 'Tencuială (mecanizată / gips / ciment)', 1),
  ('materiale', 'glet', 'Glet / chit', 2),
  ('materiale', 'vopsea', 'Vopsea lavabilă', 3),
  ('materiale', 'amorsa', 'Amorsă / grund', 4),
  ('materiale', 'sapa', 'Șapă / autonivelant', 5),
  ('materiale', 'termo', 'Termosistem / adeziv polistiren', 6),
  ('materiale', 'hidro', 'Hidroizolații / spumă / poliuree', 7),
  ('materiale', 'email', 'Email / lac / lemn', 8),
  ('materiale', 'indus', 'Anticoroziv / ignifug (industrial)', 9),
  ('materiale', 'marcaje', 'Marcaje rutiere', 10),
  ('scule', 'galeata', 'Găleată + mixer', 1),
  ('scule', 'betoniera', 'Betonieră', 2),
  ('scule', 'masina', 'Mașină de tencuit', 3),
  ('scule', 'sapa', 'Pompă de șapă', 4),
  ('scule', 'airless', 'Airless / pistol', 5),
  ('scule', 'import', 'Pompă ieftină (import)', 6),
  ('scule', 'graco', 'Graco', 7),
  ('scule', 'alta', 'Altă marcă profesională', 8),
  ('echipa', 'singur', 'Singur', 1),
  ('echipa', 'e23', '2–3 oameni', 2),
  ('echipa', 'e48', '4–8 oameni', 3),
  ('echipa', 'e9', '9+ oameni', 4),
  ('volum', 'l12', '1–2', 1),
  ('volum', 'l35', '3–5', 2),
  ('volum', 'l6', '6 sau mai multe', 3),
  ('supr', 'm30', 'Sub 30 mp', 1),
  ('supr', 'm60', '30–60 mp', 2),
  ('supr', 'm100', '60–100 mp', 3),
  ('supr', 'm100p', 'Peste 100 mp', 4),
  ('supr', 'nustiu', 'Nu știe', 5),
  ('dece', 'pret', 'Preț investiție', 1),
  ('dece', 'volum', 'Volum mic', 2),
  ('dece', 'mici', 'Lucrări mici, dese', 3),
  ('dece', 'ieftina', 'Echipă ieftină disponibilă', 4),
  ('dece', 'nustie', 'Nu știe / nu are încredere', 5),
  ('dece', 'exp', 'Experiență proastă cu o mașină', 6),
  ('dece', 'curatare', 'Curățare / timp pierdut', 7),
  ('dece', 'clientul', 'Clientul nu plătește diferența', 8),
  ('dece', 'service', 'Service / piese', 9),
  ('dece', 'neinc', 'Nu a încercat niciodată', 10),
  ('obiectii', 'scump', 'Prea scump', 1),
  ('obiectii', 'complicat', 'Prea complicat', 2),
  ('obiectii', 'service', 'Service / piese', 3),
  ('obiectii', 'sedescurca', 'Se descurcă și așa', 4),
  ('obiectii', 'aredeja', 'Are deja utilaj (alt furnizor)', 5),
  ('obiectii', 'faralucrari', 'Nu are destule lucrări', 6),
  ('obiectii', 'incredere', 'Nu are încredere în distribuitor', 7),
  ('obiectii', 'maiieftin', 'Găsește mai ieftin', 8),
  ('obiectii', 'nudecide', 'Nu decide el', 9),
  ('obiectii', 'finantare', 'Nu are cum să finanțeze', 10),
  ('pretMod', 'mp', 'Pe mp', 1),
  ('pretMod', 'zi', 'Pe zi de lucru', 2),
  ('pretMod', 'forfet', 'Forfetar', 3),
  ('pretMod', 'nustiu', 'Nu am aflat', 4),
  ('calcul', 'niciodata', 'Niciodată', 1),
  ('calcul', 'ochi', 'Din ochi', 2),
  ('calcul', 'hartie', 'Pe hârtie', 3),
  ('calcul', 'cifre', 'Cu cifre (cost/mp)', 4),
  ('atragere', 'maimult', 'Mai mult pe zi cu aceiași oameni', 1),
  ('atragere', 'termene', 'Termene mai scurte', 2),
  ('atragere', 'calitate', 'Calitate constantă', 3),
  ('atragere', 'efort', 'Mai puțin efort fizic', 4),
  ('atragere', 'pierderi', 'Mai puține pierderi de material', 5),
  ('atragere', 'mari', 'Lucrări mai mari', 6),
  ('atragere', 'curatare', 'Curățare mai rapidă', 7),
  ('atragere', 'nimic', 'Nimic acum', 8),
  ('decide', 'singur', 'Decide singur', 1),
  ('decide', 'influ', 'Influențează', 2),
  ('decide', 'nu', 'Nu decide', 3),
  ('decide', 'nustiu', 'Nu am aflat', 4),
  ('cand', 'acum', 'Luna asta', 1),
  ('cand', 'l13', 'În 1–3 luni', 2),
  ('cand', 'l3p', 'Peste 3 luni', 3),
  ('cand', 'nustiu', 'Nu știe', 4),
  ('esc', 'compat', 'Ce material merge pe ce pompă', 1),
  ('esc', 'model', 'Ce model să aleagă', 2),
  ('esc', 'pret', 'Preț / ofertă', 3),
  ('esc', 'service', 'Service / piese', 4),
  ('esc', 'demo', 'Demo la fața locului', 5),
  ('etapa', 'cunoscut', 'Cunoscut', 1),
  ('etapa', 'reconectat', 'Reconectat', 2),
  ('etapa', 'interes', 'Are interes', 3),
  ('etapa', 'demo', 'Demo / test', 4),
  ('etapa', 'oferta', 'Ofertă', 5),
  ('etapa', 'client', 'Client', 6),
  ('etapa', 'pierdut', 'Nu acum', 7);
